server:
  port: 80

zuul:
  routes:
    caspa-pico-server:
      path: /**
      url: http://localhost:8080/
      sensitive-headers:
    influxdb:
      path: /grafana/**
      url: http://localhost:3000/grafana
      sensitiveHeaders:
    mongodb:
      path: /mongodb/**
      url: mongodb://localhost:27017
      sensitive-headers: