server:
  port: 80

zuul:
  add-host-header: true
  routes:
    caspa-pico-server:
      path: /**
      url: http://localhost:8080/
      sensitive-headers:
    grafana:
      path: /grafana/**
      url: http://localhost:3000/grafana
      sensitiveHeaders: